### PR TITLE
.NET upgrade and removal of Covid APIs 

### LINKED ISSUE #42: Remove end of life COVID-19 Travel Restrictions API
## Description

The Covid-19 travel restriction API has been end of life by August 31st according to the [documentation](https://developers.amadeus.com/self-service/category/covid-19-and-travel-safety/api-doc/travel-restrictions). Requests against the endpoint will result in an Error 404 and therefore the API should be removed from the SDK. 

## Steps to Reproduce

1. Try to execute Unit test "Travel Restriction Test".
2. Review 404 HTTP error in failed test results.

__Expected Behavior__: Travel Restriction calls should no longer be supported

__Actual Behavior__: Calls are still supported but will result in 404

__Stable Behavior?__  Yes, happens all the time ^^

I will propose an easy fix for this along with a .NET 6 upgrade.

### PR DESCRIPTION
**Pull request by abeckDev**
Fixes #42 

## Description

This pull request includes the following changes:

- Upgraded all the projects and their dependencies to .NET 6
- Removed end of life travel restriction API as mentioned in #42 and #41 

## Motivation and Context

Since .NET Core 3.1 is out of support since December 13th 2022 we should consider upgrading it to the latest LTS release of .NET. See [.NET Versions](https://dotnet.microsoft.com/en-us/download/dotnet). Also removed the end of life APIs after @tsolakoua mentioned it in PR #41. The APIs are deprecated as stated on the [Documentation of Amadeus](https://developers.amadeus.com/self-service/category/covid-19-and-travel-safety/api-doc/travel-restrictions). See #42 for details.

## How to Test

Next to only removing things, I did no changes to the core logic. All the test went through and my first test were successful as well. 

## Types of Changes

- Removed capabilities  (breaking change)
- Updated .NET Version and dependencies (breaking change)

## Checklist

Remove this if you have done all of these:

- [x] Ensure all tests pass
- [x]  Add any changes to the README and Changelog.md
- [x]  Ensure this PR only changes what it is intended to change

### CODE REVIEW

**Comment by tsolakoua** [comment]
Thanks a lot @abeckDev for your contribution! It seems that the workflow fails!

**Comment by abeckDev** [comment]
Thanks for approving the workflow and I am happy to help. It seems that there are some hardcoded paths to netcoreapp3.1 directories in the workflow that I have overseen. Let me take a look into this one and I update the actions accordingly.

**Comment by abeckDev** [comment]
@tsolakoua thank you again for reviewing the request and sorry for the spam. I realised to late that I tried to debug the actions on the branch that was linked to this PR 😞.

However, I updated the GitHub Actions and could validate the build one successful. For the sonarcloud one, I depend on your repos secret and can only guess that I fixed the problem. 

I changed the following things in the actions: 

* Transformed the actions from windows workers to ubuntu-latest --> Linux builds are more easier to debug and more or less becoming the default for .NET build these days. 
* Removed NugetRestore and MSBuild parts and replaced them with the dotnet CLI --> This is best practice from the .NET.
* community and specially the dotnet restore brings in more benefit before nuget restore since it, among others, can also restore project dependencies and not just NuGetPackages.
* Also changed the file paths and options to linux style.

Ask: 

- [ ] Please cancel all the builds except the last one --> This one should at least work for the build job and give us further insights for the sonarcloud one.
- [ ] Review the changes to the actions and give me feedback if the switch to linux workers is a feasible way --> Reach out in case there are any questions regarding the change.

**Comment by abeckDev** [comment]
It seems that the integration tests are failing because there are outdated credentials. My local unit tests are working and therefore I assume that this can be fixed by changing the repository secrets to up to date API credentials. 
@tsolakoua Can you update the credentials and also check the sonarcloud connection? I seems there is a similar problem.

**Comment by tsolakoua** [comment]
Hello @abeckDev , indeed that must be the case :) I will try to make some time for that in the next few days!

**Pull request merged**
